spring.application.name=LifeSense

jwt.secret=rafascg2334fnc234lsv9sywoerw4230
jwt.expiration=86400

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/lifesense_db
spring.datasource.username=root
spring.datasource.password=myapp